services:
  - type: web
    name: secure-share-backend
    env: python
    buildCommand: "cd api && pip install -r requirements.txt"
    startCommand: "cd api && python main.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DB_NAME
        sync: false
      - key: PORT
        sync: false

  - type: web
    name: secure-share-frontend
    env: node
    buildCommand: "cd web && npm install && npm run build"
    startCommand: "cd web && npx serve -s build -l 3000"
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_NAME
        sync: false
      - key: REACT_APP_VERSION
        sync: false
      - key: GENERATE_SOURCEMAP
        sync: false